<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Eureka">
      <HintPath>..\..\src\Eureka\bin\Debug\net8.0-windows\win-x64\Eureka.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
